version: "3.7"

services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: db-dockerfile
    ports:
      - 5432:5432
    volumes:
      - ./docker/db/:/var/lib/postgresql/data
